vich_uploader:
    db_driver: orm

    mappings:
        tutorials:
           uri_prefix: /images/tutorials
           upload_destination: '%kernel.project_dir%/public/images/tutorials'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        content:
            uri_prefix: /images/content
            upload_destination: '%kernel.project_dir%/public/images/content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
